export const DNDTypes = {
	TAB: "TAB",
	BOOKMARK: "BOOKMARK",
	SUB_BOOKMARK: "SUB_BOOKMARK",
	SUB_FOLDER: "SUB_FOLDER",
	FOLDER: "FOLDER"
};

export const pathTypes = {
	QUESTS: "QUESTS",
	APPS: "APPS",
	SERVERS: "SERVERS",
	SHOP: "SHOP",
	NITRO: "NITRO",
	HOME: "HOME",
	CHANNEL: "CHANNEL",
	DM: "DM"
};